#!/bin/bash
AIROOTFS=$ARCHLIVE_DIR/airootfs
AURDIR=$AIROOTFS/opt/aur

mkdir $AURDIR || "/tmp/aur already exists"
cd $AURDIR
curl -sL https://aur.archlinux.org/cgit/aur.git/snapshot/broadcom-wl.tar.gz | tar xvz
cd broadcom-wl
chmod 777 -R $AURDIR
sudo -u nobody makepkg -s
