#!/bin/bash
set -x
set -e

CMD=${1:-all}

source common
source vars

run() {
  source tasks/$1
}

step_all() {
  run 00_partition.sh
  run 01_install.sh
  run 03_fstab.sh
  run 04_chroot.sh
  run 05_cleanup.sh
  #run 06_reboot.sh
}

step_$CMD $ARGS




